bundler_args: ""
script: "bundle exec rake spec"
rvm:
  - 2.0.0
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.2.gemfile
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.5
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_5.2.gemfile
