name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        activerecord: ['4.2', '5.2']
        include:
        exclude:
          - ruby: '2.6'
            activerecord: '4.2'
          - ruby: '2.7'
            activerecord: '4.2'
          - ruby: '3.0'
            activerecord: '4.2'
    name: ruby${{ matrix.ruby }} activerecord${{ matrix.activerecord }}
    env:
      BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.activerecord }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
