name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        activerecord: ['4.2', '5.0', '5.1', '5.2']
        include:
        exclude:
        - ruby: '2.6'
          activerecord: '4.2'
        - ruby: '2.7'
          activerecord: '4.2'
        - ruby: '3.0'
          activerecord: '4.2'
    name: ruby${{ matrix.ruby }} activerecord${{ matrix.activerecord }}
    # TODO: use setup-ruby with bundler-cache: true ... but that fails on always using deployment mode
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    # TODO: use regular bundle install once we are done with bundler v1
    - run: gem install matching_bundle && matching_bundle install
      env:
        BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.activerecord }}.gemfile
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
    - run: bundle exec rake spec
      env:
        BUNDLE_GEMFILE: gemfiles/activerecord_${{ matrix.activerecord }}.gemfile
